// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: cmd/go_grpc/go_grpc.proto

package go_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Greet int32

const (
	Greet_HELLO    Greet = 0
	Greet_WHATS_UP Greet = 1
)

// Enum value maps for Greet.
var (
	Greet_name = map[int32]string{
		0: "HELLO",
		1: "WHATS_UP",
	}
	Greet_value = map[string]int32{
		"HELLO":    0,
		"WHATS_UP": 1,
	}
)

func (x Greet) Enum() *Greet {
	p := new(Greet)
	*p = x
	return p
}

func (x Greet) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Greet) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_go_grpc_go_grpc_proto_enumTypes[0].Descriptor()
}

func (Greet) Type() protoreflect.EnumType {
	return &file_cmd_go_grpc_go_grpc_proto_enumTypes[0]
}

func (x Greet) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Greet.Descriptor instead.
func (Greet) EnumDescriptor() ([]byte, []int) {
	return file_cmd_go_grpc_go_grpc_proto_rawDescGZIP(), []int{0}
}

type HelloGrpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Greets []Greet `protobuf:"varint,2,rep,packed,name=greets,proto3,enum=exgogrpc.Greet" json:"greets,omitempty"`
}

func (x *HelloGrpcRequest) Reset() {
	*x = HelloGrpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_go_grpc_go_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloGrpcRequest) ProtoMessage() {}

func (x *HelloGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_go_grpc_go_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloGrpcRequest.ProtoReflect.Descriptor instead.
func (*HelloGrpcRequest) Descriptor() ([]byte, []int) {
	return file_cmd_go_grpc_go_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *HelloGrpcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloGrpcRequest) GetGreets() []Greet {
	if x != nil {
		return x.Greets
	}
	return nil
}

type HelloGrpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply  string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Reply2 string `protobuf:"bytes,2,opt,name=reply2,proto3" json:"reply2,omitempty"`
}

func (x *HelloGrpcResponse) Reset() {
	*x = HelloGrpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_go_grpc_go_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloGrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloGrpcResponse) ProtoMessage() {}

func (x *HelloGrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_go_grpc_go_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloGrpcResponse.ProtoReflect.Descriptor instead.
func (*HelloGrpcResponse) Descriptor() ([]byte, []int) {
	return file_cmd_go_grpc_go_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *HelloGrpcResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *HelloGrpcResponse) GetReply2() string {
	if x != nil {
		return x.Reply2
	}
	return ""
}

var File_cmd_go_grpc_go_grpc_proto protoreflect.FileDescriptor

var file_cmd_go_grpc_go_grpc_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6d, 0x64, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x78, 0x67,
	0x6f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x4f, 0x0a, 0x10, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x67, 0x72, 0x65, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x65, 0x78, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x06,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x73, 0x22, 0x41, 0x0a, 0x11, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47,
	0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x2a, 0x20, 0x0a, 0x05, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x57, 0x48, 0x41, 0x54, 0x53, 0x5f, 0x55, 0x50, 0x10, 0x01, 0x32, 0x52, 0x0a, 0x08, 0x45,
	0x78, 0x47, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x12, 0x46, 0x0a, 0x09, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x47, 0x72, 0x70, 0x63, 0x12, 0x1a, 0x2e, 0x65, 0x78, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x65, 0x78, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_go_grpc_go_grpc_proto_rawDescOnce sync.Once
	file_cmd_go_grpc_go_grpc_proto_rawDescData = file_cmd_go_grpc_go_grpc_proto_rawDesc
)

func file_cmd_go_grpc_go_grpc_proto_rawDescGZIP() []byte {
	file_cmd_go_grpc_go_grpc_proto_rawDescOnce.Do(func() {
		file_cmd_go_grpc_go_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_go_grpc_go_grpc_proto_rawDescData)
	})
	return file_cmd_go_grpc_go_grpc_proto_rawDescData
}

var file_cmd_go_grpc_go_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_go_grpc_go_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_go_grpc_go_grpc_proto_goTypes = []interface{}{
	(Greet)(0),                // 0: exgogrpc.Greet
	(*HelloGrpcRequest)(nil),  // 1: exgogrpc.HelloGrpcRequest
	(*HelloGrpcResponse)(nil), // 2: exgogrpc.HelloGrpcResponse
}
var file_cmd_go_grpc_go_grpc_proto_depIdxs = []int32{
	0, // 0: exgogrpc.HelloGrpcRequest.greets:type_name -> exgogrpc.Greet
	1, // 1: exgogrpc.ExGoGrpc.HelloGrpc:input_type -> exgogrpc.HelloGrpcRequest
	2, // 2: exgogrpc.ExGoGrpc.HelloGrpc:output_type -> exgogrpc.HelloGrpcResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_go_grpc_go_grpc_proto_init() }
func file_cmd_go_grpc_go_grpc_proto_init() {
	if File_cmd_go_grpc_go_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_go_grpc_go_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloGrpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_go_grpc_go_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloGrpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_go_grpc_go_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_go_grpc_go_grpc_proto_goTypes,
		DependencyIndexes: file_cmd_go_grpc_go_grpc_proto_depIdxs,
		EnumInfos:         file_cmd_go_grpc_go_grpc_proto_enumTypes,
		MessageInfos:      file_cmd_go_grpc_go_grpc_proto_msgTypes,
	}.Build()
	File_cmd_go_grpc_go_grpc_proto = out.File
	file_cmd_go_grpc_go_grpc_proto_rawDesc = nil
	file_cmd_go_grpc_go_grpc_proto_goTypes = nil
	file_cmd_go_grpc_go_grpc_proto_depIdxs = nil
}
